config/routes.rb
Rails.application.routes.draw do
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  get '/sign_up' => 'users#new'
  post '/sign_up' => 'users#create'

  root 'pages#index'
  get '/about' => 'pages#about'
  get '/lookup' => 'pages#lookup'

  get '/change_password' => 'users#pass'
  post '/change_password' => 'users#password'

  get '/show_all_cars' => 'cars#showall'
  get '/show_all_garages' => 'garages#showall'

  get '/show_my_cars' => 'cars#showmy'
  get '/show_my_garages' => 'garages#showmy'

  get '/show_garage' => 'cars#showgarage'

  get '/move' => 'garages#move'
  post '/move' => 'garages#movein'

  get '/moveout' => 'garages#moveo'
  post '/moveout' => 'garages#moveout'

  resources :garages
  resources :cars
  resources :users
  resources :comments
  resources :pages
  resources :morepictures

  # Note some of these routes may now be redundant - to be checked and cleaned up
end

app/models/car.rb
class Car < ActiveRecord::Base
	belongs_to :user
	has_many :comments
	has_many :morepictures
	has_and_belongs_to_many :garages
	mount_uploader :primary_picture, PictureUploader
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :car
end

app/models/garage.rb
class Garage < ActiveRecord::Base
	belongs_to :user
	has_and_belongs_to_many :cars
end

app/models/morepicture.rb
class Morepicture < ActiveRecord::Base
	belongs_to :car
	mount_uploader :extra_picture, PictureUploader
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :cars
	has_many :garages
	has_secure_password
	validates :username, :uniqueness => true
	validates :first_name, :last_name, :email, :username, :password_confirmation, :presence => true, :on => :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

 	before_action :authenticate

  private

  def current_user
    @current_user = User.find_by(id: session[:user_id])
  end

  helper_method :current_user

  def logged_in?
    !!current_user
  end
  
	helper_method :logged_in?

  def authenticate
  	redirect_to login_path unless logged_in?
	end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

	def show
		@car = Car.find(params[:id])
		@comments = Comment.where(:car_id => @car.id)
		@comment = Comment.new
		@pictures = Morepicture.where(:car_id => @car.id)
		@picture = Morepicture.new
	end

	def showall # Change this to index
		@cars = Car.all
	end

	def showmy
		@cars = Car.where(:user_id => @current_user.id)
	end

	def showgarage
		cars = Car.all
		@garage = Garage.find(params[:garage_id])
		@cars_in_garage = @garage.cars
	end

	def new
		@car = Car.new
	end

	def create
		@car = Car.new(car_params)
		@car.user_id = @current_user.id

		if @car.save
			redirect_to car_path(@car.id), :notice => 'New car created successfully'
		else
			flash.notice = 'Car not created, please try again'
			render :new
		end
	end

	def edit
		@car = Car.find(params[:id])
	end

	def update
		@car = Car.find(params[:id])
		@car.update(car_params)
		redirect_to car_path :notice => 'Car updated successfully'
	end

	def destroy
		@car = Car.find(params[:id])
		@car.destroy
		redirect_to root_path :notice => 'Car deleted successfully'
	end

	private

	def car_params
		params.require(:car).permit(:make, :model, :year, :colour, :body_type, :engine, :transmission, :wheels_tyres, :other_details, :primary_picture)
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def new
		@comment = Comment.new
	end

	def create
		@comment = Comment.new
		@comment.comment_details = params[:comment][:comment_details]
		@comment.car_id = params[:comment][:car_id]
	
		if @comment.save
			redirect_to car_path(params[:comment][:car_id])
		else
			flash.notice = 'Comment not saved, please try again'
			render :new
		end
	end

end

app/controllers/garages_controller.rb
class GaragesController < ApplicationController

	def show
		@garage = Garage.find(params[:id])
	end

	def showall # Change this to index
		@garages = Garage.all
	end

	def showmy
		@garages = Garage.where(:user_id => @current_user.id)
	end

	def move
		@cars = Car.where(:user_id => @current_user.id)
		@garage = Garage.find params[:garage_id]
	end

	def movein
		@garage = Garage.find(params[:car][:garage_id])
		@car = Car.find(params[:garage][:car_ids])

		if !@garage.cars.include?(@car) # Ensure the car is not alredy in the garage
			@garage.cars << @car
			@garage.save
			redirect_to garage_path(@garage.id), :notice => 'Car moved in successfully'
		else
			flash.notice = 'This car is aready in this garage, please choose another car'
			render :move
		end
	end

	def moveo
		@cars = Car.where(:user_id => params[:garage_id])
		@garage = Garage.find params[:garage_id]
	end

	def moveout
		garage = Garage.find(params[:car][:garage_id])
		car = Car.find(params[:car][:car_ids])
		garage.cars.delete(car)
		redirect_to garage_path(garage.id), :notice => 'Car moved out successfully'
	end

	def new
		@garage = Garage.new
	end

	def create
		@garage = Garage.new(garage_params)
		@garage.user_id = @current_user.id

		if @garage.save
			redirect_to garage_path(@garage.id), :notice => 'New garage created successfully'
		else
			flash.notice = 'Garage not created, please try again'
			render :new
		end
	end

	def edit
		@garage = Garage.find(params[:id])
	end

	def update
		@garage = Garage.find(params[:id])
		@garage.update(garage_params)
		redirect_to garage_path, :notice => 'Garage updated successfully'
	end

	def destroy
		@garage = Garage.find(params[:id])
		@garage.destroy
		redirect_to root_path, :notice => 'Garage deleted successfully'
	end

	private

	def garage_params
		params.require(:garage).permit(:name, :theme, :details)
	end
end

app/controllers/morepictures_controller.rb
class MorepicturesController < ApplicationController

	def new
		@picture = Morepicture.new
	end

	def create
		@picture = Morepicture.new
		@picture.extra_picture = params[:morepicture][:extra_picture]
		@picture.car_id = params[:morepicture][:car_id]
		
		if @picture.save
			redirect_to car_path(params[:morepicture][:car_id])
		else
			flash.notice = 'Picture not saved, please try again'
			render :new
		end
	end

	def destroy
		@picture = Morepicture.find(params[:id])
		@picture.destroy
		redirect_to car_path(@picture.car_id), :notice => 'Picture deleted successfully'
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	skip_before_action :authenticate

	def index
		@garages = Garage.all
	end

	def about
	end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  skip_before_action :authenticate

  def new
  end

  def create
    user = User.where(:username => params[:username]).first
    # user = User.find_by(name: params[:username])
    if user.present? && user.authenticate(params[:password])
      # correct password
      session[:user_id] = user.id
      redirect_to root_path
    else
      # incorrect password
      redirect_to login_path, :notice => 'Incorrect username or password, please try again'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	skip_before_action :authenticate, :only => [:new, :create]

	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end

	def create
		# Change this to use user_params (don't forget to add the password info in the user_params def below)
		@user = User.new
		@user.first_name = params[:first_name]
		@user.last_name = params[:last_name]
		@user.email = params[:email]
		@user.username = params[:username]
		@user.password = params[:password]
		@user.password_confirmation = params[:password_confirmation]

		if @user.save
			session[:user_id] = @user.id
			redirect_to root_path, :notice => 'New account created successfully'
		else
			flash.notice = 'Account not created, please try again'
			render :new
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		current_user.update(user_params)
		redirect_to user_path :notice => 'Details updated successfully'
	end

	def pass
	end

	def password
		@current_user.password = params[:new_password]
		@current_user.password_confirmation = params[:password_confirmation]
		@current_user.save
		redirect_to user_path(@current_user.id), :notice => 'Password updated successfully'
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		redirect_to root_path :notice => 'Your account has been deleted successfully'
	end

	private

	def user_params
		params.require(:user).permit(:first_name, :last_name, :email, :username)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/edit.html.erb
<h2>Edit Car</h2>

<div class="underlay1 well">
	<%= form_for @car do |f| %>

	<p><%= f.label :name, 'Car name' %></p>
	<p class="darken_text"><%= f.text_area :name, cols: 100, rows: 1 %></p>

	<p><%= f.label :make, 'Car make' %></p>
	<p class="darken_text"><%= f.text_area :make, cols: 100, rows: 1 %></p>

	<p><%= f.label :moddel, 'Car model' %></p>
	<p class="darken_text"><%= f.text_area :moddel, cols: 100, rows: 1 %></p>

	<p><%= f.label :year, 'Year of manufacture' %></p>
	<p class="darken_text"><%= f.text_area :year, cols: 100, rows: 1 %></p>

	<p><%= f.label :colour, 'Colour' %></p>
	<p class="darken_text"><%= f.text_area :colour, cols: 100, rows: 1 %></p>

	<p><%= f.label :body_type, 'Body type' %></p>
	<p class="darken_text"><%= f.text_area :body_type, cols: 100, rows: 1 %></p>

	<p><%= f.label :engine, 'Engine details' %></p>
	<p class="darken_text"><%= f.text_area :engine, cols: 100, rows: 1 %></p>

	<p><%= f.label :transmission, 'Transmission details' %></p>
	<p class="darken_text"><%= f.text_area :transmission, cols: 100, rows: 1 %></p>

	<p><%= f.label :wheels_tyres, 'Wheel and tyre details' %></p>
	<p class="darken_text"><%= f.text_area :wheels_tyres, cols: 100, rows: 1 %></p>

	<p><%= f.label :other_details, 'Other details' %></p>
	<p class="darken_text"><%= f.text_area :other_details, cols: 100, rows: 10 %></p>

	<p><%= f.label :primary_picture, 'Primary picture' %></p>
	<p><%= f.file_field :primary_picture %></p>

	<button class="btn btn-primary">Update</button>

	<% end %>
</div>

app/views/cars/new.html.erb
<h2>New Car</h2>

<div class="underlay1 well">
	<%= form_for @car do |f| %>

	<p><%= f.label :name, 'Car name' %></p>
	<p class="darken_text"><%= f.text_area :name, cols: 100, rows: 1 %></p>

	<p><%= f.label :make, 'Car make' %></p>
	<p class="darken_text"><%= f.text_area :make, cols: 100, rows: 1 %></p>

	<p><%= f.label :moddel, 'Car model' %></p>
	<p class="darken_text"><%= f.text_area :moddel, cols: 100, rows: 1 %></p>

	<p><%= f.label :year, 'Year of manufacture' %></p>
	<p class="darken_text"><%= f.text_area :year, cols: 100, rows: 1 %></p>

	<p><%= f.label :colour, 'Colour' %></p>
	<p class="darken_text"><%= f.text_area :colour, cols: 100, rows: 1 %></p>

	<p><%= f.label :body_type, 'Body type' %></p>
	<p class="darken_text"><%= f.text_area :body_type, cols: 100, rows: 1 %></p>

	<p><%= f.label :engine, 'Engine details' %></p>
	<p class="darken_text"><%= f.text_area :engine, cols: 100, rows: 1 %></p>

	<p><%= f.label :transmission, 'Transmission details' %></p>
	<p class="darken_text"><%= f.text_area :transmission, cols: 100, rows: 1 %></p>

	<p><%= f.label :wheels_tyres, 'Wheel and tyre details' %></p>
	<p class="darken_text"><%= f.text_area :wheels_tyres, cols: 100, rows: 1 %></p>

	<p><%= f.label :other_details, 'Other details' %></p>
	<p class="darken_text"><%= f.text_area :other_details, cols: 100, rows: 10 %></p>

	<p><%= f.label :primary_picture, 'Primary picture' %></p>
	<p><%= f.file_field :primary_picture %></p>

	<button class="btn btn-success">Create</button>

	<% end %>
</div>

app/views/cars/show.html.erb
<h2><%= @car.name %></h2>

<div class="add_margin"><img src="<%= @car.primary_picture %>"></div>

<% @pictures.each do |p| %>
	<div class ="size1">
		<img src="<%= p.extra_picture %>">
		<% if @car.user_id == @current_user.id %>
			<button class="btn btn-danger btn-xs"><%= link_to 'Delete picture', p, :method => :delete, :data => {:confirm => 'Are you sure?'}%></button>
		<% end %>
	</div>
<% end %>

<div class="underlay1 well">
	<h3>Details for this car</h3>
	<p>Car make: <%= @car.make %></p>
	<p>Car model: <%= @car.moddel %></p>
	<p>Year of manufacture: <%= @car.year %></p>
	<p>Colour: <%= @car.colour %></p>
	<p>Body type: <%= @car.body_type %></p>
	<p>Engine details: <%= @car.engine %></p>
	<p>Transmission details: <%= @car.transmission %></p>
	<p>Wheel and tyre details: <%= @car.wheels_tyres %></p>
	<p>Other details: <%= @car.other_details %></p>
</div>

<div class="underlay1 well">
	<h3>Comments for this car</h3>

	<% @comments.each do |c| %>
		<p><%= c.comment_details %></p>
	<% end %>

	<h3>Add a comment</h3>
	<p>Please note comments cannot be edited or deleted so write carefully!</p>

	<%= form_for @comment do |f| %>
		<p>
			<div class="darken_text"><%= f.text_area :comment_details, cols: 100, rows: 10%></div>
			<%= f.hidden_field :car_id, :value => @car.id %>
		</p>
		<button class="btn btn-success">Post comment</button>
	<% end %>
</div>

<% if @car.user_id == @current_user.id %>
	<div class="underlay1 well">
		<h3>Add a picture</h3>
		<%= form_for @picture do |f| %>
			<%= f.file_field :extra_picture %>
			<%= f.hidden_field :car_id, :value => @car.id %>
		<button class="btn btn-primary">Upload</button>
		<% end %>
	</div>
<% end %>


<button class="btn btn-default"><%= link_to 'Show garages this car resides in', garage_path %></button>

<% if @car.user_id == @current_user.id %>
	<button class="btn btn-warning"><div><%= link_to 'Edit car', edit_car_path %></div></button>
	<button class="btn btn-danger"><%= link_to 'Delete car', @car, :method => :delete, :data => {:confirm => 'Are you sure?'}%></button>
<% end %>

app/views/cars/showall.html.erb
<h2>All Cars</h2>

<p>Click on a car to view its details</p>

<% @cars.each do |car| %>
	<div class="size1"><a href="<%= car_path(car) %>"><img src="<%= car.primary_picture %>"></a></div>
<% end %>

app/views/cars/showgarage.html.erb
<h2>Cars in this Garage</h2>

<% if @cars_in_garage.first %>
	<% @cars_in_garage.each do |car| %>
	  <div class="size1"><a href="<%= car_path(car) %>"><img src="<%= car.primary_picture %>"></a></div>
	<% end %>
<% else %>
	<p>There are no cars in this garage</p>
	<% if @garage.user_id == @current_user.id %>
		<button class="btn btn-default btn-lg"><%= link_to 'Move a car into this garage', move_path(:garage_id => @garage.id) %></button>
	<% end %>
<% end %>

app/views/cars/showmy.html.erb
<h2>My Cars</h2>

<% if @cars.first %>
	<p>Click on a car to view its details</p>
<% end %>

<% if @cars.first %>
	<% @cars.each do |car| %>
		<div class="size1"><a href="<%= car_path(car) %>"><img src="<%= car.primary_picture %>"></a></div>
	<% end %>
<% else %>
		<p>You do not have any cars yet</p>
		<button class="btn btn-success btn-lg"><%= link_to 'New Car', new_car_path %></button>
<% end %>

app/views/comments/new.html.erb
<h2>New comment</h2>

<%= form_for @comment do |f| %>
	<p>
		<%= f.label :comment_details %>
		<div class="darken_text"><%= f.text_field :comment_details %></div>
	</p>
	<button class="btn btn-success">Post comment</button>
<% end %>

<!-- Note this page is no longer needed - this code has been added to the Show Car page instead -->

app/views/garages/edit.html.erb
<h2>Edit Garage</h2>

<div class="underlay1 well">
	<%= form_for @garage do |f| %>

	<p><%= f.label :name, 'Garage name' %></p>
	<p class="darken_text"><%= f.text_area :name, cols: 100, rows: 1 %></p>

	<p><%= f.label :theme, 'Garage theme' %></p>
	<p class="darken_text"><%= f.text_area :theme, cols: 100, rows: 1 %></p>

	<p><%= f.label :details, 'Garage details' %></p>
	<p class="darken_text"><%= f.text_area :details, cols: 100, rows: 10 %></p>

	<button class="btn btn-primary">Update</button>

	<% end %>
</div>

app/views/garages/move.html.erb
<h2>Move Car In</h2>

<% if true # @cars.first should be here but crashes the app when trying to add the same car again%>
	<div class="underlay1 well">
		<h3>Please select a car to move into the garage</h3>
		<%= form_tag move_path do %>
		<%= collection_radio_buttons :garage, :car_ids, @current_user.cars, :id, :name %>
		<%= hidden_field_tag :garage_id, @garage.id, :name => 'car[garage_id]' %>
		<button class="btn btn-primary">Select</button>
		<% end %>
	</div>
<% else %>
	<p>You have no cars to move</p>
	<button class="btn btn-primary btn-lg"><%= link_to 'New Car', new_car_path %></button>
<% end %>

app/views/garages/moveo.html.erb
<h2>Move Car Out</h2>

<% if @cars.first # Does not behave properly - still finds cars when there are none in the garage %>
	<div class="underlay1 well">
		<h3>Please select a car to move out of the garage</h3>
		<%= form_tag moveout_path do %>
		<%= collection_radio_buttons :car, :car_ids, @garage.cars, :id, :name %>
		<%= hidden_field_tag :garage_id, @garage.id, :name => 'car[garage_id]' %>
		<button class="btn btn-primary">Select</button>
		<% end %>
	</div>
<% else %>
	<p>You have no cars to move out of this garage</p>
<% end %>

app/views/garages/new.html.erb
<h2>New Garage</h2>

<div class="underlay1 well">
	<%= form_for @garage do |f| %>

	<p><%= f.label :name, 'Garage name' %></p>
	<p class="darken_text"><%= f.text_area :name, cols: 100, rows: 1 %></p>

	<p><%= f.label :theme, 'Garage theme' %></p>
	<p class="darken_text"><%= f.text_area :theme, cols: 100, rows: 1 %></p>

	<p><%= f.label :details, 'Garage details' %></p>
	<p class="darken_text"><%= f.text_area :details, cols: 100, rows: 10 %></p>

	<button class="btn btn-success">Create</button>

<% end %>
</div>

app/views/garages/show.html.erb
<h2>Show Garage</h2>

<div class="underlay1 well">
	<p>Garage name: <%= @garage.name %></p>
	<p>Gragae theme: <%= @garage.theme %></p>
	<p>Garage details: <%= @garage.details %></p>
</div>

<button class="btn btn-default"><%= link_to 'Show cars in this garage', show_garage_path(:garage_id => @garage.id) %></button>

<% if @garage.user_id == @current_user.id %>
	<button class="btn btn-default"><%= link_to 'Move a car into this garage', move_path(:garage_id => @garage.id) %></button>
	<button class="btn btn-default"><%= link_to 'Move a car out of this garage', moveout_path(:garage_id => @garage.id) %></button>
	<button class="btn btn-warning"><%= link_to 'Edit garage', edit_garage_path %></button>
	<button class="btn btn-danger"><%= link_to 'Delete garage', @car, :method => :delete, :data => {:confirm => 'Are you sure?'}%></button>
<% end %>

app/views/garages/showall.html.erb
<h2>All Garages</h2>

<p>Click on a garage to view its details</p>

<% @garages.each do |gar| %>
	<p><h3><a href="<%= garage_path(gar) %>"><%= gar.name %></a></h3></p>
<% end %>

app/views/garages/showmy.html.erb
<h2>My Garages</h2>

<% if @garages.first %>
	<p>Click on a garage to view its details</p>
<% end %>

<% if @garages.first %>
	<% @garages.each do |gar| %>
		<p><h3><a href="<%= garage_path(gar) %>"><%= gar.name %></a></h3></p>
	<% end %>
<% else %>
	<p>You do not have any garages yet</p>
	<button class="btn btn-success btn-lg"><%= link_to 'New Garage', new_garage_path %></button>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cargarage</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<div class="underlay2 well">
			<nav>
				<ul class="nav nav-pills">
					<li><%= link_to 'Home', root_path %></li>
					<li><%= link_to 'About', '/about' %></li>

					<% if logged_in? %> 
						<li><%= link_to 'New Car', new_car_path %></li>
						<li><%= link_to 'New Garage', new_garage_path %></li>
						<li><%= link_to 'Show All Cars', show_all_cars_path %></li>
						<li><%= link_to 'Show All Garages', show_all_garages_path %></li>
						<li><%= link_to 'Show My Cars', show_my_cars_path %></li>
						<li><%= link_to 'Show My Garages', show_my_garages_path %></li>
						<li><%= link_to 'My Account', user_path(current_user.id) %></li>
					  <li><%= link_to 'logout', login_path, :method => :delete, :data => {:confirm => 'are you sure?'} %></li>
					  <li class="middle"><%= link_to 'Get details for popular makes and models (opens in new window)', lookup_path, :target => '_blank' %></li>
				  <% else %>
				  	<li><%= link_to 'Sign Up', sign_up_path %></li>
				  	<li><%= link_to 'login', login_path %></li>
				  <% end %>
				</ul>
			</nav>
		</div>

		<% if logged_in? %>
			<p>Welcome, &nbsp<%= current_user.first_name %><p>
		<% end %>

		<% flash.each do |key, value| %>
			<% if value == 'Incorrect username or password, please try again' || value == 'Account not created, please try again' %>
				<div class="underlay4 well"><%= value %></div>
			<% else %>
				<div class="underlay2 well"><%= value %></div>
			<% end %>
		<% end %>

		<%= yield %>

	</div>
</body>
</html>

app/views/morepictures/new.html.erb
<h2>New Picture</h2>

<!-- This file is not needed after all -->

app/views/pages/about.html.erb
<h2>About Car Garage</h2>

<p>Here is a web app that allows you to post details of your cars to share with others. You can put up photos and technical details of your cars, create and manipulate garages to put your cars into (analogous to photo albums) as well as gain access to detailed technical information about popular car makes and models to assist you in comlpeting your car entries.</p>

app/views/pages/index.html.erb
<h1>Car Garage Home</h1>

<% if logged_in? %> 
	<p>Click on a garage for more details</p>
	<% @garages.each do |garage| %>
		<p><h3><a href="<%= garage_path(garage) %>"><%= garage.name %></a></h3></p>
	<% end %>
<% end %>

app/views/session/new.html.erb
<h1>Login</h1>

<%= form_tag '/login' do %>

<p><%= label_tag :username %></p>
<p><div class="darken_text"><%= text_field_tag :username %></div></p>

<p><%= label_tag :password %>
<p><div class="darken_text"><%= password_field_tag :password %></div></p>

<button class="btn btn-success">Login</button>

<% end %>

app/views/users/edit.html.erb
<h2>Change Account Details</h2>

<%= form_for @user do |f| %>
	<p><%= label_tag :first_name %></p>
	<p class="darken_text"><%= f.text_field :first_name %></p>

	<p><%= label_tag :last_name %></p>
	<p class="darken_text"><%= f.text_field :last_name %></p>

	<p><%= label_tag :email %></p>
	<p class="darken_text"><%= f.text_field :email %></p>

	<p><%= label_tag :username %></p>
	<p class="darken_text"><%= f.text_field :username %></p>

	<button class="btn btn-warning">Update</button>
<% end %>

app/views/users/new.html.erb
<h2>Sign Up</h2>

<% if !@user.errors.empty? %>
	<div class="underlay1 well">
		<%= @user.errors.full_messages.each do |msg| %>
			<h3 class="error red_text"><%= msg %></h3>
		<% end %>
	</div>
<% end %>

<%= form_tag '/sign_up' do |f| %>
	<p><%= label_tag :first_name %></p>
	<p class="darken_text"><%= text_field_tag :first_name %></p>

	<p><%= label_tag :last_name %></p>
	<p class="darken_text"><%= text_field_tag :last_name %></p>

	<p><%= label_tag :email %></p>
	<p class="darken_text"><%= text_field_tag :email %></p>

	<p><%= label_tag :username %></p>
	<p class="darken_text"><%= text_field_tag :username %></p>

	<p><%= label_tag :password %></p>
	<p class="darken_text"><%= password_field_tag :password %></p>

	<p><%= label_tag :password_confirmation %></p>
	<p class="darken_text"><%= password_field_tag :password_confirmation %></p>

	<button class="btn btn-success">Sign Up</button>
<% end %>

app/views/users/pass.html.erb
<h2>Change Password</h2>

<%= form_tag change_password_path do |f| %>
	<p><%= label_tag 'Old password' %></p>
	<p class="darken_text"><%= password_field_tag :password %></p>

	<p><%= label_tag 'New password' %></p>
	<p class="darken_text"><%= password_field_tag :new_password %></p>

	<p><%= label_tag 'Confirm new password' %></p>
	<p class="darken_text"><%= password_field_tag :password_confirmation %></p>

	<button class="btn btn-warning">Change</button>
<% end %>

app/views/users/show.html.erb
<h2>My Account Detais</h2>

<div class="underlay1 well">
	<p>First name: <%= @user.first_name %></p>
	<p>Last name: <%= @user.last_name %></p>
	<p>Email address: <%= @user.email %></p>
	<p>Username: <%= @user.username %></p>
</div>

<button class="btn btn-default"><%= link_to 'Edit details', edit_user_path %></button>
<button class="btn btn-warning"><%= link_to 'Change password', change_password_path %></button>
<button class="btn btn-danger"><%= link_to 'Close account', @user, :method => :delete, :data => {:confirm => 'Are you sure you want to close your account?'}%></button>